search:
  - name: "Loan Category"
    key: "loanCategaory"
    type: "text"
    errorText: "Vehicle category is required"
    defaultValue: INVOICE_BASED_LOAN
    required: true
    summary: This attribute refers to categorizing loans based on whether they are intended for personal use or are meant for invoices.
  - name: "Payment Tags"
    key: "paymentTagsSearch"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        display: false
        BUYER_FINDER_FEES_TYPE: percent-annualized
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        display: false
        DELAY_INTEREST: 2.5
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
        OFFLINE_CONTRACT: "true"
    errorText: "Payment tags is required"
    required: true
    summary: Describes tags

personal_info_form:
  - name: "BPP ID"
    key: "bpp_id"
    type: "select"
    extractionPath: "`businessPayload[]{key: bpp_id, value: bpp_id}`"
    defaultValueExpression: "data.session.bpp_id"
    errorText: "BPP ID is required"
    required: true
    summary: It explains the Explains the subscriber of the Seller App (BPP).
  - name: "BPP URI"
    key: "bpp_uri"
    type: "select"
    extractionPath: "`businessPayload[?(bpp_id === '${formData.bpp_id || data.session.bpp_id}')]{key: bpp_uri, value: bpp_uri}`"
    errorText: "BPP URI is required"
    required: true
    summary: The subscriber URL of the Seller App (BPP) is the endpoint that accepts callbacks from the Buyer App (BAP).
  - name: Form Url
    key: personalFormUrl
    type: "select"
    extractionPath: "`businessPayload[?(bpp_id === '${formData.bpp_id || data.session.bpp_id}')].formData[]{key: formUrl, value: formUrl}`"
    summary: Needs to be filled to get the submission id
  - name: "ProviderId"
    key: "providerId"
    type: "select"
    extractionPath: "`businessPayload[?(bpp_id === '${formData.bpp_id || data.session.bpp_id}')].formData[]{key: providerId, value: providerId}`"
    errorText: "Provider Id is required"
    required: true
    summary: This refers to the unique id of the provider whose catalog items have been selected.
  - name: "Form Id"
    key: "formId"
    type: "select"
    extractionPath: "`businessPayload[?(bpp_id === '${formData.bpp_id || data.session.bpp_id}')].formData[]{key: id, value: id}`"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller
  - name: "Item Id"
    key: "itemId"
    type: "select"
    extractionPath: "`businessPayload[?(bpp_id === '${formData.bpp_id || data.session.bpp_id}')].formData[]{key: itemId, value: itemId}`"
    errorText: "item Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

search_1:
  - name: Submission ID
    key: personalInfoSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission
  - name: "Consent Status"
    key: "search1FormStatus"
    type: "select"
    defaultValue: "SUCCESS"
    defaultOptions:
      - key: "SUCCESS"
        value: "SUCCESS"
        dummyData: "hahaha"
    errorText: "Please select a field"
    required: true
    summary: Submission Id revieved after form submission

search_2:
  - name: "Consent Status"
    key: "search2FormStatus"
    type: "select"
    defaultValue: "APPROVED"
    defaultOptions:
      - key: "APPROVED"
        value: "APPROVED"
    errorText: "Please select a field"
    required: true
    summary: Submission Id revieved after form submission

select:
  - name: "Parent Id"
    key: "parentItemId"
    type: "select"
    extractionPath: "`businessPayload[].itemDetails[]{key: parentItemId, value: parentItemId}`"
    errorText: "Form Id is required"
    required: true
    summary: Parent Id is the uniqure id of the seller
  - name: "Item Id"
    key: "selectItemID"
    type: "select"
    extractionPath: "`businessPayload[].itemDetails[]{key: itemID, value: itemID}`"
    errorText: "Form Id is required"
    required: true
    summary: Item Id is the uniqure id of the seller

loan_amount_adjust_form:
  - name: Form Url
    key: adjustAmountFormUrl
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: formUrl, value: formUrl}`"
    submissionIdFieldKey: adjustAmountSubmissionId
    summary: Needs to be filled to get the submission id
  - name: "Form Id"
    key: "formIdAmountAdjustForm"
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: id, value: id}`"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

select_1:
  - name: Submission ID
    key: adjustAmountSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission
  - name: "Consent Status"
    key: "selectFormStatus"
    type: "select"
    defaultValue: "SUCCESS"
    defaultOptions:
      - key: "SUCCESS"
        value: "SUCCESS"
    errorText: "Please select a field"
    required: true
    summary: Submission Id revieved after form submission

customer_info_form:
  - name: Form Url
    key: customerInfoFormUrl
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: formUrl, value: formUrl}`"
    summary: Need to be filled to get the submission id
  - name: "Form Id"
    key: "customerInfoFormId"
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: id, value: id}`"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

init:
  - name: Submission ID
    key: customerInfoSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission
  - name: "Consent Status"
    key: "initFormStatus"
    type: "select"
    defaultValue: "SUCCESS"
    defaultOptions:
      - key: "SUCCESS"
        value: "SUCCESS"
    errorText: "Please select a field"
    required: true
    summary: Submission Id revieved after form submission
  - name: "Payment Status"
    key: "paymentStatus"
    type: "select"
    defaultValue: "NOT-PAID"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentType"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Tags"
    key: "paymentTagsInit"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        BUYER_FINDER_FEES_TYPE: percent-annualized
        display: false
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        SETTLEMENT_TYPE: "neft"
        display: false
        DELAY_INTEREST: "5"
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
        SETTLEMENT_AMOUNT: "12312"
        OFFLINE_CONTRACT: "true"
    errorText: "Payment Tags is required"
    required: true
    summary: Starting stop of the journey location

kyc_form:
  - name: Form Url
    key: kycFormUrl
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: formUrl, value: formUrl}`"
    summary: Need to be filled to get the submission id
  - name: "Form Id"
    key: "kycFormId"
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: id, value: id}`"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

init_1:
  - name: Submission ID
    key: kycSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission
  - name: "Payment Status"
    key: "paymentStatusInit1"
    type: "select"
    defaultValue: "NOT-PAID"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentType"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location

account_details_form:
  - name: Form Url
    key: accointDetailsFormUrl
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: formUrl, value: formUrl}`"
    submissionIdFieldKey: accointDetailsFormSubmissionId
    summary: Need to be filled to get the submission id
  - name: "Form Id"
    key: "accointDetailsFormId"
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: id, value: id}`"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

init_2:
  - name: Submission ID
    key: accointDetailsFormSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission

e_mandate_details_form:
  - name: Form Url
    key: eMandateDetailsFormUrl
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: formUrl, value: formUrl}`"
    summary: Need to be filled to get the submission id
  - name: "Form Id"
    key: "eMandateDetailsFormId"
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: id, value: id}`"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

init_3:
  - name: Submission ID
    key: eMandateDetailsSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission

loan_agreement_form:
  - name: Form Url
    key: loanAgreementFormUrl
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: formUrl, value: formUrl}`"
    summary: Need to be filled to get the submission id
  - name: "Form Id"
    key: "loanAgreementFormId"
    type: "select"
    extractionPath: "`businessPayload[].formData[]{key: id, value: id}`"
    errorText: "Form Id is required"
    required: true
    summary: Provider Id is the uniqure id of the seller

confirm:
  - name: Submission ID
    key: loanAgreementSubmissionId
    type: "text"
    errorText: "Submission Id is required"
    required: true
    summary: Submission Id revieved after form submission
  - name: "Payment Status"
    key: "paymentStatusConfirm"
    type: "select"
    defaultValue: "PAID"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentTypeConfirm"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Tags"
    key: "paymentTagsConfirm"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        BUYER_FINDER_FEES_TYPE: percent-annualized
        display: false
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        SETTLEMENT_TYPE: "neft"
        display: false
        DELAY_INTEREST: "5"
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
        SETTLEMENT_AMOUNT: "12312"
        OFFLINE_CONTRACT: "true"
    errorText: "Payment Tags is required"
    required: true
    summary: Starting stop of the journey location

update:
  - name: Order Id
    key: orderId
    type: "text"
    errorText: "Order Id is required"
    required: true
    summary: Order Id revieved after form submission
  - name: Order status
    key: fulfillmentStatus
    type: "select"
    defaultValue: "APPROVED"
    defaultOptions:
      - key: "APPROVED"
        value: "APPROVED"
    errorText: "Please select a field"
    required: true
    summary: Order status is the status of fulfillment

status:
  - name: Order Id
    key: orderId
    type: "text"
    errorText: "Order Id is required"
    required: true
    summary: Order Id revieved after form submission
