search:
  type: "search"
  target: "GATEWAY"
  executed: false
  shouldRender: true
  config: "search"
  nextRequest: "on_search"
  preRequest: null
  isCollapsed: true

on_search:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search"
  nextRequest: "personal_info_form"
  preRequest: "search"
  isCollapsed: true

personal_info_form:
  type: "form"
  formUrlKey: personalFormUrl
  executed: false
  shouldRender: false
  config: "personal_info_form"
  nextRequest: "search_1"
  preRequest: "on_search"
  isCollapsed: true

search_1:
  type: "search"
  target: "NP"
  executed: false
  shouldRender: false
  config: "search_1"
  nextRequest: "on_search_1"
  preRequest: "personal_info_form"
  isCollapsed: true

on_search_1:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search_1"
  nextRequest: search_2
  preRequest: "search_1"
  isCollapsed: true

search_2:
  type: "search"
  target: "NP"
  executed: false
  shouldRender: false
  config: "search_2"
  nextRequest: "on_search_2"
  preRequest: "on_search_1"
  isCollapsed: true
  # isSkipable:
  #   condition: "session.search1FormStatus === 'SUCCESS'"
  #   nextRequest: "select"

on_search_2:
  type: "on_search"
  executed: false
  shouldRender: false
  config: "on_search_2"
  nextRequest: select
  preRequest: "search_2"
  isCollapsed: true

select:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select"
  nextRequest: "on_select"
  preRequest: "on_search_2"
  isCollapsed: true

on_select:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select"
  nextRequest: loan_amount_adjust_form
  preRequest: "select"
  isCollapsed: true

loan_amount_adjust_form:
  type: "form"
  formUrlKey: adjustAmountFormUrl
  executed: false
  shouldRender: false
  config: "loan_amount_adjust_form"
  nextRequest: select_1
  preRequest: "on_select"
  isCollapsed: true

select_1:
  type: "select"
  target: "NP"
  executed: false
  shouldRender: false
  config: "select_1"
  nextRequest: "on_select_1"
  preRequest: "loan_amount_adjust_form"
  isCollapsed: true

on_select_1:
  type: "on_select"
  executed: false
  shouldRender: false
  config: "on_select_1"
  nextRequest: customer_info_form
  preRequest: "select_1"
  isCollapsed: true

customer_info_form:
  type: "form"
  formUrlKey: customerInfoFormUrl
  executed: false
  shouldRender: false
  config: "customer_info_form"
  nextRequest: init
  preRequest: "on_select_1"
  isCollapsed: true

init:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init"
  nextRequest: on_init
  preRequest: "customer_info_form"
  isCollapsed: true

on_init:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init"
  nextRequest: kyc_form
  preRequest: "init"
  isCollapsed: true

kyc_form:
  type: "form"
  formUrlKey: kycFormUrl
  executed: false
  shouldRender: false
  config: "kyc_form"
  nextRequest: init_1
  preRequest: "on_init"
  isCollapsed: true

init_1:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init_1"
  nextRequest: on_init_1
  preRequest: "kyc_form"
  isCollapsed: true

on_init_1:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init_1"
  nextRequest: account_details_form
  preRequest: "init_1"
  isCollapsed: true

account_details_form:
  type: "form"
  formUrlKey: accointDetailsFormUrl
  executed: false
  shouldRender: false
  config: "account_details_form"
  nextRequest: init_2
  preRequest: "on_init_1"
  isCollapsed: true

init_2:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init_2"
  nextRequest: on_init_2
  preRequest: "account_details_form"
  isCollapsed: true

on_init_2:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init_2"
  nextRequest: e_mandate_details_form
  preRequest: "init_2"
  isCollapsed: true

e_mandate_details_form:
  type: "form"
  formUrlKey: eMandateDetailsFormUrl
  executed: false
  shouldRender: false
  config: "e_mandate_details_form"
  nextRequest: init_3
  preRequest: "on_init_2"
  isCollapsed: true

init_3:
  type: "init"
  target: "NP"
  executed: false
  shouldRender: false
  config: "init_3"
  nextRequest: on_init_3
  preRequest: "e_mandate_details_form"
  isCollapsed: true

on_init_3:
  type: "on_init"
  executed: false
  shouldRender: false
  config: "on_init_3"
  nextRequest: loan_agreement_form
  preRequest: "init_3"
  isCollapsed: true

loan_agreement_form:
  type: "form"
  formUrlKey: loanAgreementFormUrl
  executed: false
  shouldRender: false
  config: "loan_agreement_form"
  nextRequest: confirm
  preRequest: "on_init_3"
  isCollapsed: true

confirm:
  type: "confirm"
  target: "NP"
  executed: false
  shouldRender: false
  config: "confirm"
  nextRequest: on_confirm
  preRequest: "loan_agreement_form"
  isCollapsed: true

on_confirm:
  type: "on_confirm"
  executed: false
  shouldRender: false
  config: "on_confirm"
  nextRequest: update
  preRequest: "confirm"
  isCollapsed: true

update:
  type: "update"
  target: "NP"
  executed: false
  shouldRender: false
  config: "update"
  nextRequest: on_update
  preRequest: "on_confirm"
  isCollapsed: true

on_update:
  type: "on_update"
  executed: false
  shouldRender: false
  config: "on_update"
  nextRequest: status
  preRequest: "update"
  isCollapsed: true

status:
  type: "status"
  target: "NP"
  executed: false
  shouldRender: false
  config: "status"
  nextRequest: on_status
  preRequest: "on_update"
  isCollapsed: true

on_status:
  type: "on_status"
  executed: false
  shouldRender: false
  config: "on_status"
  nextRequest: null
  preRequest: "status"
  isCollapsed: true
