server:
  port: 80
  variables:
    dev:
      callbackUrl: "https://2273-59-145-217-117.ngrok-free.app"
      stagingGatewayurl: "https://staging.gateway.proteantech.in/"
      signingPrivateKey: "Un205TSOdDXTq8E+N/sJOLJ8xalnzZ1EUP1Wcv23sKx70fOfFd4Q2bzfpzPQ+6XZhZv65SH7Pr6YMk8SuFHpxQ=="
      bapId: "mobility-staging.ondc.org"
      uniqueKeyId: "UK-MOBILITY"
    prod:
      callbackUrl: "https://2273-59-145-217-117.ngrok-free.app"
      stagingGatewayurl: "https://staging.gateway.proteantech.in/"
      signingPrivateKey: "Un205TSOdDXTq8E+N/sJOLJ8xalnzZ1EUP1Wcv23sKx70fOfFd4Q2bzfpzPQ+6XZhZv65SH7Pr6YMk8SuFHpxQ=="
      bapId: "mobility-staging.ondc.org"
      uniqueKeyId: "UK-MOBILITY"
flows:
  - summary: Metro - Station Code Based Flow
    id: metro-flow-1
    domain: ONDC:TRV11
    sessionData:
      collectedBy: BAP
      bankAccountNumber: "123456789"
      virtualPaymentAddress: "adasd@okiciic"
      bankCode: "fj3jf9ij3f02"
    input:
      $ref: ./configs/metro-flow-1/input.yaml
    protocol:
      $ref: ./configs/metro-flow-1/protocolMapping.yaml
    calls:
      $ref: ./configs/metro-flow-1/protocolCalls.yaml
    additioalFlows:
      - key: metro cancel flow
        value: metro-cancel-flow-1
  - summary: metro cancel flow
    shouldDispaly: false # check
    id: metro-cancel-flow-1
    domain: ONDC:TRV11
    input:
      $ref: ./configs/metro-cancel-flow-1/input.yaml
    protocol:
      $ref: ./configs/metro-cancel-flow-1/protocolMapping.yaml
    calls:
      $ref: ./configs/metro-cancel-flow-1/protocolCalls.yaml
  - summary: Metro - Station Code Based Flow(without select call)
    id: metro-flow-2
    domain: ONDC:TRV11
    sessionData:
      collectedBy: BAP
      bankAccountNumber: "123456789"
      virtualPaymentAddress: "adasd@okiciic"
      bankCode: "fj3jf9ij3f02"
    input:
      $ref: ./configs/metro-flow-2/input.yaml
    protocol:
      $ref: ./configs/metro-flow-2/protocolMapping.yaml
    calls:
      $ref: ./configs/metro-flow-2/protocolCalls.yaml
  - summary: on demand complete flow
    domain: ONDC:TRV10
    id: ondemand-flow-1
    input:
      $ref: ./configs/ondemand-flow-1/input.yaml
    protocol:
      $ref: ./configs/ondemand-flow-1/protocolMapping.yaml
    calls:
      $ref: ./configs/ondemand-flow-1/protocolCalls.yaml
