search_route:
  - name: "Vehical Category"
    key: "vehicalCategory"
    type: "text"
    errorText: "Vehical category is required"
  - name: "Payment Tags"
    key: "paymentTagsSearch"
    type: "multiline"
    errorText: "Payment tags is required"

search_trip:
  - name: "BPP URI"
    key: "bpp_uri"
    type: "text"
    error: "BPP URI is required"
  - name: "BPP ID"
    key: "bpp_id"
    type: "text"
    error: "BPP ID is required"
  - name: "Start stop"
    key: "startStop"
    type: "text"
    error: "Start stop is required"
  - name: "End stop"
    key: "endStop"
    type: "text"
    error: "End stop is required"

select:
  - name: "Item id"
    key: "itemId"
    type: "text"
    errorText: "Item id is required"
  - name: "Quantity"
    key: "quantity"
    type: "text"
    errorText: "Quantity is required"
  - name: "Provider id"
    key: "providerId"
    type: "text"
    errorText: "Provider id is required"

init:
  - name: "Name"
    key: "name"
    type: "text"
    errorText: "Name is required"
  - name: "Email"
    key: "email"
    type: "text"
    errorText: "Email is required"
  - name: "Phone"
    key: "phone"
    type: "text"
    errorText: "Phone is required"
  - name: "Collected By"
    key: "collectedBy"
    type: "text"
    errorText: "Collected By is required"
  - name: "Payment Status"
    key: "paymentStatus"
    type: "text"
    errorText: "Payment Status is required"
  - name: "Payment Type"
    key: "paymentType"
    type: "text"
    errorText: "Payment Type is required"
  - name: "Bank Code"
    key: "banckCode"
    type: "text"
    errorText: "Bank Code is required"
  - name: "Bank Account Number"
    key: "banckAccountNumber"
    type: "text"
    errorText: "Bank Account Number is required"
  - name: "Virtual Payment Address"
    key: "virtualPaymentAddress"
    type: "text"
    errorText: "Virtual Payment Address is required"
  - name: "Payment Tags"
    key: "paymentTagsInit"
    type: "multiline"
    errorText: "Payment Tags is required"

confirm:
  - name: "Payment Id"
    key: "paymentId"
    type: "text"
    errorText: "Payment Id is required"
  - name: "Collected By"
    key: "collectedByConfirm"
    type: "text"
    errorText: "Collected By is required"
  - name: "Payment Status"
    key: "paymentStatusConfirm"
    type: "text"
    errorText: "Payment Status is required"
  - name: "Payment Type"
    key: "paymentTypeConfirm"
    type: "text"
    errorText: "Payment Type is required"
  - name: "Transcation Id"
    key: "transcationId"
    type: "text"
    errorText: "Transcation Id is required"
  - name: "Amount"
    key: "amount"
    type: "text"
    errorText: "Amount is required"
  - name: "Currency"
    key: "currency"
    type: "text"
    errorText: "Currency is required"
  - name: "Payment Tags"
    key: "paymentTagsConfirm"
    type: "multiline"
    errorText: "Payment Tags is required"

status:
  - name: "Order Id"
    key: "orderId"
    type: "text"
    errorText: "Order Id is required"
