search_route:
  - name: "Vehicle Category"
    key: "vehicleCategaory"
    type: "text"
    errorText: "Vehicle category is required"
    required: true
    summary: Vehicle category for which ticket needs to be booked
  - name: "Payment Tags"
    key: "paymentTagsSearch"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        BUYER_FINDER_FEES_TYPE: percent-annualized
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        DELAY_INTEREST: 2.5
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
    errorText: "Payment tags is required"
    required: true
    summary: Vehicle category for which ticket needs to be booked

search_trip:
  - name: "BPP URI"
    key: "bpp_uri"
    type: "select"
    extractionPath: "businessPayload[]{key: bpp_uri, value: bpp_uri}"
    errorText: "BPP URI is required"
    required: true
    summary: BPP URI is the base url for the seller endpoints
  - name: "BPP ID"
    key: "bpp_id"
    type: "select"
    extractionPath: "businessPayload[]{key: bpp_id, value: bpp_id}"
    errorText: "BPP ID is required"
    required: true
    summary: BPP ID is the uniqure id of the seller
  - name: "Start stop"
    key: "startStop"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].location[]{key: locationName, value: locationName}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "Start stop is required"
    required: true
    summary: Starting stop of the journey location
  - name: "End stop"
    key: "endStop"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].location[]{key: locationName, value: locationName}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "End stop is required"
    required: true
    summary: Starting stop of the journey location

select:
  - name: "Item id"
    key: "itemId"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].items[]{key: name, value: id}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "Item id is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Quantity"
    key: "quantity"
    type: "text"
    errorText: "Quantity is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Provider id"
    key: "providerId"
    type: "select"
    extractionPath: "businessPayload[?(bpp_id === '${bpp_id}')].items[]{key: providerId, value: providerId}"
    extractionPathReplace: "${bpp_id}"
    extractionPathReplaceWith: formData.bpp_id
    errorText: "Provider id is required"
    required: true
    summary: Starting stop of the journey location

init:
  - name: "Name"
    key: "name"
    type: "text"
    errorText: "Name is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Email"
    key: "email"
    type: "text"
    errorText: "Email is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Phone"
    key: "phone"
    type: "text"
    errorText: "Phone is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Status"
    key: "paymentStatus"
    type: "select"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentType"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Tags"
    key: "paymentTagsInit"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        BUYER_FINDER_FEES_TYPE: percent-annualized
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        DELAY_INTEREST: 2.5
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
    errorText: "Payment Tags is required"
    required: true
    summary: Starting stop of the journey location

confirm:
  - name: "Payment Id"
    key: "paymentId"
    type: "text"
    errorText: "Payment Id is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Status"
    key: "paymentStatus"
    type: "select"
    defaultOptions:
      - key: "PAID"
        value: "PAID"
      - key: "NOT-PAID"
        value: "NOT-PAID"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Type"
    key: "paymentType"
    type: "select"
    defaultValue: "PRE-ORDER"
    defaultOptions:
      - key: "PRE-ORDER"
        value: "PRE-ORDER"
      - key: "PRE-FULFILLMENT"
        value: "PRE-FULFILLMENT"
      - key: "ON-FULFILLMENT"
        value: "ON-FULFILLMENT"
      - key: "POST-FULFILLMENT"
        value: "POST-FULFILLMENT"
      - key: "ON-ORDER"
        value: "ON-ORDER"
    errorText: "Please select a field"
    required: true
    summary: Starting stop of the journey location
  - name: "Transcation Id"
    key: "paymentTranscationId"
    type: "text"
    errorText: "Transcation Id is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Amount"
    key: "amount"
    type: "text"
    errorText: "Amount is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Currency"
    key: "currency"
    type: "text"
    defaultValue: INR
    errorText: "Currency is required"
    required: true
    summary: Starting stop of the journey location
  - name: "Payment Tags"
    key: "paymentTagsConfirm"
    type: "multiline"
    defaultValue:
      BUYER_FINDER_FEES:
        BUYER_FINDER_FEES_TYPE: percent-annualized
        BUYER_FINDER_FEES_PERCENTAGE: "1"
      SETTLEMENT_TERMS:
        DELAY_INTEREST: 2.5
        STATIC_TERMS: "https://bap.credit.becknprotocol.io/personal-banking/loans/personal-loan"
    errorText: "Payment Tags is required"
    required: true
    summary: Starting stop of the journey location

status:
  - name: "Order Id"
    key: "orderId"
    type: "text"
    errorText: "Order Id is required"
    required: true
    summary: Starting stop of the journey location
