cancel:
  - name: "Order Id"
    key: "orderIdCancel"
    type: "text"
    errorText: "Order Id is required"
  - name: "Cancellation Reason"
    key: "cancelReason"
    type: "select"
    defaultOptions:
      - key: "0"
        value: "0"
      - key: "1"
        value: "1"
      - key: "2"
        value: "2"
      - key: "3"
        value: "3"
      - key: "4"
        value: "4"
      - key: "5"
        value: "5"
      - key: "6"
        value: "6"
      - key: "7"
        value: "7"
    errorText: "Please select a field"
  - name: "Cancel Type"
    key: "cancelType"
    type: "select"
    defaultOptions:
      - key: "SOFT_CANCEL"
        value: "SOFT_CANCEL"
      - key: "CONFIRM_CANCEL"
        value: "CONFIRM_CANCEL"
    errorText: "Please select a field"
