protocol:
  cancel:
    mapping:
      - beckn_key: context.bap_id
        value: session.bap_id
      - beckn_key: context.bap_uri
        value: session.bap_uri
      - beckn_key: context.bpp_id
        value: session.bpp_id
      - beckn_key: context.bpp_uri
        value: session.bpp_uri
      - beckn_key: context.location.country.code
        value: session.country
      - beckn_key: context.location.city.code
        value: session.cityCode
      - beckn_key: context.transaction_id
        value: session.currentTransactionId
      - beckn_key: context.message_id
        value: messageId
      - beckn_key: context.timestamp
        value: timestamp
      - beckn_key: context.domain
        value: session.domain
      - beckn_key: context.version
        value: session.version
      - beckn_key: context.ttl
        value: session.ttl
      - beckn_key: context.action
        value: action

      - beckn_key: message.order_id
        value: data.orderIdCancel
      - beckn_key: message.cancellation_reason_id
        value: data.cancelReason
      - beckn_key: message.descriptor.code
        value: data.cancelType
      - beckn_key: message.descriptor.name
        value: cancelName

  on_cancel:
    mapping:
      business_key: "status"
      extractionPath: "message.order.status"
