update:
  - name: Order Id
    key: orderId
    type: "text"
    errorText: "Order Id is required"
    required: true
    summary: Order Id revieved after form submission
  - name: Amount
    key: prePartAmount
    type: "text"
    errorText: "Amount is required"
    required: true
    summary: Amount for update call
    defaultValue: "92720"
